// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PubInvest.HouseConfig.Data;

#nullable disable

namespace PubInvest.HouseConfig.Data.Migrations
{
    [DbContext(typeof(HouseConfigDbContext))]
    partial class HouseConfigDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.CircuitRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("LengthMetres")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmainId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("WattsPerMetre")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.HasKey("Id");

                    b.HasIndex("SubmainId");

                    b.ToTable("Circuits");
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.DeviceChannelRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChannelIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CircuitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceInstanceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSpare")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.HasIndex("DeviceInstanceId", "ChannelIndex")
                        .IsUnique();

                    b.ToTable("DeviceChannels");
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.DeviceInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModuleWidth")
                        .HasColumnType("integer");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StartSlot")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmainId")
                        .HasColumnType("uuid");

                    b.Property<string>("TerminalRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubmainId", "RowIndex", "StartSlot")
                        .IsUnique();

                    b.ToTable("DeviceInstances");
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.DeviceTypeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChannelCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaxLoadPerChannelW")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxTotalLoadW")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModuleWidth")
                        .HasColumnType("integer");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.EnclosureTypeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("IpRating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.Property<int>("SlotsPerRow")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.PanelRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LayoutVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmainId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmainId", "LayoutVersion");

                    b.ToTable("PanelRevisions");
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.PositionOverrideRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StartSlot")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmainId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmainId", "Label")
                        .IsUnique();

                    b.ToTable("PositionOverrides");
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.RuleSetRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("RuleSets");
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.Submain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EnclosureTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FeedCableSize")
                        .HasColumnType("text");

                    b.Property<int>("LayoutVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("OriginBreakerAmps")
                        .HasColumnType("integer");

                    b.Property<string>("Phase")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<Guid?>("RuleSetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Submains");
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.CircuitRow", b =>
                {
                    b.HasOne("PubInvest.HouseConfig.Data.Entities.Submain", null)
                        .WithMany("Circuits")
                        .HasForeignKey("SubmainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.DeviceChannelRow", b =>
                {
                    b.HasOne("PubInvest.HouseConfig.Data.Entities.DeviceInstance", null)
                        .WithMany("Channels")
                        .HasForeignKey("DeviceInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.DeviceInstance", b =>
                {
                    b.HasOne("PubInvest.HouseConfig.Data.Entities.Submain", null)
                        .WithMany("Devices")
                        .HasForeignKey("SubmainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.PositionOverrideRow", b =>
                {
                    b.HasOne("PubInvest.HouseConfig.Data.Entities.Submain", null)
                        .WithMany()
                        .HasForeignKey("SubmainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.Submain", b =>
                {
                    b.HasOne("PubInvest.HouseConfig.Data.Entities.Project", "Project")
                        .WithMany("Submains")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.DeviceInstance", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.Project", b =>
                {
                    b.Navigation("Submains");
                });

            modelBuilder.Entity("PubInvest.HouseConfig.Data.Entities.Submain", b =>
                {
                    b.Navigation("Circuits");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
